name: Create Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup UV with cache
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync dependencies with uv
        run: uv sync --extra docs --no-editable

      - name: Create Docs
        run: |
          uv run sphinx-autogen -o docs/source/generated docs/api_reference.rst
          uv run make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html